// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3Y07b_lTX5agxEK0NRmdhdxX5N_Sr8GE',
    appId: '1:955744685816:web:daebd877118a8c85bc350d',
    messagingSenderId: '955744685816',
    projectId: 'todo-3212',
    authDomain: 'todo-3212.firebaseapp.com',
    storageBucket: 'todo-3212.appspot.com',
    measurementId: 'G-J0KG7DE700',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9mmVp2OJyUvxIccNBWYnf8xkRZBU8Rsk',
    appId: '1:955744685816:android:ba72c2ecb65183f6bc350d',
    messagingSenderId: '955744685816',
    projectId: 'todo-3212',
    storageBucket: 'todo-3212.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS8L3xH8gOOnXyL7DMLS8vRcerENGqrvk',
    appId: '1:955744685816:ios:a28867f79d08326dbc350d',
    messagingSenderId: '955744685816',
    projectId: 'todo-3212',
    storageBucket: 'todo-3212.appspot.com',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS8L3xH8gOOnXyL7DMLS8vRcerENGqrvk',
    appId: '1:955744685816:ios:a28867f79d08326dbc350d',
    messagingSenderId: '955744685816',
    projectId: 'todo-3212',
    storageBucket: 'todo-3212.appspot.com',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3Y07b_lTX5agxEK0NRmdhdxX5N_Sr8GE',
    appId: '1:955744685816:web:bcd336990676556fbc350d',
    messagingSenderId: '955744685816',
    projectId: 'todo-3212',
    authDomain: 'todo-3212.firebaseapp.com',
    storageBucket: 'todo-3212.appspot.com',
    measurementId: 'G-LMLC9NE5JL',
  );
}
